### ISSUE TITLE
課題 箱のイラスト

### ISSUE THREAD

**Issue by HoashiTakumi** [furuhashilab/jyubako4dronemapping#11]
https://i.imgur.com/BI3oCdE.jpg

**Comment by HoashiTakumi** [comment]
![image](https://user-images.githubusercontent.com/32722374/34233708-5b89c1b4-e62a-11e7-92ea-3ea6b8b4b26c.png)

**Comment by mapconcierge** [comment]
期限過ぎても、できるだけ 提出してください！ 最終課題が最も大事です！

**Comment by HoashiTakumi** [comment]
![image](https://user-images.githubusercontent.com/32722374/35050656-aad474e0-fbe6-11e7-9fc5-86a9147ebadf.png)

**Comment by HoashiTakumi** [comment]
遅れてすみません

**Comment by HoashiTakumi** [comment]
![image](https://user-images.githubusercontent.com/32722374/35053366-3d111d94-fbed-11e7-99c1-a1adb5316390.png)

**Comment by HoashiTakumi** [comment]
![image](https://user-images.githubusercontent.com/32722374/35054878-0fe7f76c-fbf1-11e7-8b60-3eaf5bf5380b.png)

**Comment by HoashiTakumi** [comment]
* PDFファイル
https://speakerdeck.com/hoashitakumi/takumi-hoashi

**Comment by HoashiTakumi** [comment]
* pptxファイル
[フレッシャーズセミナー　ドローン.pptx](https://github.com/furuhashilab/jyubako4dronemapping/files/1640124/default.pptx)
