### ISSUE TITLE
住箱のカスタマイズ案   田中海気

### ISSUE THREAD

**Issue by Tanakaiki** [furuhashilab/jyubako4dronemapping#14]
![181ada7a-0388-422a-b37f-29ddc97c7f19](https://user-images.githubusercontent.com/32722362/34229310-20a1c190-e617-11e7-8586-e08742f11213.jpeg)

**Comment by mapconcierge** [comment]
期限過ぎても課題を提出してください！

**Comment by Tanakaiki** [comment]
![img_4749](https://user-images.githubusercontent.com/32722362/35073758-d29a0d4a-fc2d-11e7-9a67-4893b051e141.jpg)

**Comment by Tanakaiki** [comment]
![default](https://user-images.githubusercontent.com/32722362/35073775-dd61c024-fc2d-11e7-86d8-5f0790311f37.png)

**Comment by Tanakaiki** [comment]
https://speakerdeck.com/tanakaiki
