### ISSUE TITLE
住箱の活用方法(横瀬町)

### ISSUE THREAD

**Issue by Kosuke418** [furuhashilab/jyubako4dronemapping#15]
![img_4841](https://user-images.githubusercontent.com/32722339/34232768-35fbcf78-e625-11e7-8dd0-5a264fbbc135.JPG)

**Comment by Kosuke418** [comment]
![Imgur](http://i.imgur.com/dVbfCt9.jpg)

**Comment by mapconcierge** [comment]
ブランディングの命名アイディアやロゴの説明がないです。また、ver1.0 をブラッシュアップした資料も提出してください。

**Comment by Kosuke418** [comment]
# 12/21課題再提出
![default](https://user-images.githubusercontent.com/32722339/35022725-50e69c5e-fb2f-11e7-9ca2-253bdc59b0b5.png)

# ブランド名
- Farmarone
- Farm:農業 Drone:ドローンより

# ロゴの意味
- ドローンの周りに農業に関係したものを配置した

**Comment by Kosuke418** [comment]
# 1/11課題
## Farmarone
![default](https://user-images.githubusercontent.com/32722339/35023530-fa918e00-fb32-11e7-8e99-acd73e2049a9.png)

**Comment by Kosuke418** [comment]
# プレゼン資料
https://speakerdeck.com/kosukenishikawa/fs2017-doronhuo-yong-fa
