### ISSUE TITLE
住箱の活用について　15117054 佐藤文音

### ISSUE THREAD

**Issue by kkkhhh99** [furuhashilab/jyubako4dronemapping#16]
![image](https://user-images.githubusercontent.com/32722316/34232758-265145b2-e625-11e7-9ac5-8901b9ec76d8.png)

**Comment by mapconcierge** [comment]
写真の解像度、撮り方、明るさなど考慮して高品質な画像として提出してください！

**Comment by kkkhhh99** [comment]
![image](https://user-images.githubusercontent.com/32722316/34802962-de0a5ab0-f6b3-11e7-8e97-1e33755c3c98.png)

**Comment by kkkhhh99** [comment]
![image](https://user-images.githubusercontent.com/32722316/34803369-4e1a4d54-f6b6-11e7-997a-9c41f3d764ef.png)

**Comment by kkkhhh99** [comment]
![image](https://user-images.githubusercontent.com/32722316/34803881-08070dea-f6b9-11e7-860b-b4e68be12412.png)

**Comment by kkkhhh99** [comment]
![img_1286](https://user-images.githubusercontent.com/32722316/35047318-e6e8d534-fbdc-11e7-8fb9-aa3836b248d4.JPG)

**Comment by kkkhhh99** [comment]
![image](https://user-images.githubusercontent.com/32722316/35048678-1ff7faf4-fbe1-11e7-8a25-ac313c05f563.png)

**Comment by kkkhhh99** [comment]
https://speakerdeck.com/kkkhhh99/zhu-xiang-falseaideia
[mapping.pptx](https://github.com/furuhashilab/jyubako4dronemapping/files/1639388/mapping.pptx)
