### ISSUE TITLE
住箱の活用法

### ISSUE THREAD

**Issue by Yu-Kawada** [furuhashilab/jyubako4dronemapping#20]
![d42e7c23-a382-4e87-a9ee-7d539dbf6c0d](https://user-images.githubusercontent.com/32722445/34235951-69e1c7a8-e638-11e7-955e-d0342880a967.jpeg)
![Uploading 26819F1E-D9EE-448B-9E19-96862A306C0F.jpeg…]()

**Comment by Yu-Kawada** [comment]
![e0dd3896-9501-4c11-91b7-054b7baa3333](https://user-images.githubusercontent.com/32722445/34396362-2a0a0116-ebad-11e7-9633-fc26a042472f.jpeg)

**Comment by mapconcierge** [comment]
ver2 のブラッシュアップ版資料を作ってください！

**Comment by Yu-Kawada** [comment]
Speaker Deck
 https://speakerdeck.com/wky555/yu-kawada

PDF
[住箱 活用法.pdf](https://github.com/furuhashilab/jyubako4dronemapping/files/1640064/default.pdf)


元ファイル
[住箱 活用法.pptx](https://github.com/furuhashilab/jyubako4dronemapping/files/1640063/default.pptx)

**Comment by Yu-Kawada** [comment]
ロゴ画像

![rogo](https://user-images.githubusercontent.com/32722445/35058275-c5c92b4c-fbfa-11e7-824f-2794843343f8.png)
