### ISSUE TITLE
# 1/11(木)の課題

### ISSUE THREAD

**Issue by mapconcierge** [furuhashilab/jyubako4dronemapping#21]
# 1/11(木)の課題
1. 前回のロゴデザインをパソコン使って、清書してみてください。ツールはPowerPoint, Illustrator, Inkscape, Keynote, その他自分の使いやすいツールを自由に選んでOKとします。

2. 最終課題(1/11 発表してもらいます)
今回のSnowPeak住箱アイディアを、一人3分の持ち時間前提でプレゼン資料を作成してください。PowerPoint, Keynotes どちらでもいいですが、最終的にPDFファイルで出力して Speakerdeck で公開してください。Speskerdeckはデフォルト非公開設定なので、必ずPublish設定で公開してください。
https://speakerdeck.com/ 

提出先は前回同様、今までの自分の GitHub Issue に追記投稿してください。ロゴ画像の埋め込み、元ファイル(PPTファイル等)もアップロード。Speakerdeck はPermalinkと元ファイル(PPT, KEY)をIssueに追記投稿してください。ファイルのアップロードは場合によってはZIP圧縮が必要です。

## 次回(1/18)が最終回です。全員必ず出席してください！

**Comment by Yoshinori747** [comment]
# Speakerdeck
[https://speakerdeck.com/yoshinori747/camping-dot-d](url)
# 元ファイル
[camping.d.pptx](https://github.com/furuhashilab/jyubako4dronemapping/files/1623312/camping.d.pptx)
