### ISSUE TITLE
住箱の案

### ISSUE THREAD

**Issue by Kenshiro0121** [furuhashilab/jyubako4dronemapping#22]
提出が遅れて申し訳ありません。
![9c6690c1-b2bb-4b78-8809-cb48b6929753](https://user-images.githubusercontent.com/32722519/34805020-fae62668-f6be-11e7-8e12-435043713de8.jpeg)

**Comment by Kenshiro0121** [comment]
18117224 吉田賢志朗

**Comment by Kenshiro0121** [comment]
![default](https://user-images.githubusercontent.com/32722519/34866475-ff5a9ad8-f7bf-11e7-9a18-5eca96055f69.png)
[フレッシャーズセミナー　最終課題.pptx](https://github.com/furuhashilab/jyubako4dronemapping/files/1625408/default.pptx)

**Comment by mapconcierge** [comment]
＞ @Kenshiro0121 
PPTファイルは PDF出力して
https://speakerdeck.com/ で公開してください！
