### ISSUE TITLE
住箱　カスタマイズ　15117090　二野瀬　成朗

### ISSUE THREAD

**Issue by shigeruninose** [furuhashilab/jyubako4dronemapping#24]
![img_2933 2](https://user-images.githubusercontent.com/32722319/35037756-c9bad96a-fbbb-11e7-9ce1-3a5e8aed9b24.jpg)

**Comment by shigeruninose** [comment]
![2018-01-17 21 15 52](https://user-images.githubusercontent.com/32722319/35042382-c473b4e4-fbcb-11e7-9c3c-4fe5f36aeea1.png)

**Comment by shigeruninose** [comment]
speakerdeck URL
[https://speakerdeck.com/shigeruninose/zhu-xiang-kasutamaizu](url)
元のファイル
[住箱 カスタマイズ.pdf](https://github.com/furuhashilab/jyubako4dronemapping/files/1639652/default.pdf)

**Comment by shigeruninose** [comment]
speakerdeck URL
[https://speakerdeck.com/shigeruninose/shigeruninose(url)
元のファイル
[](url)

**Comment by mapconcierge** [comment]
speakerdeck が Publish モードになっていません！ ＞ @shigeruninose

**Comment by shigeruninose** [comment]
https://speakerdeck.com/shigeruninose/zhu-xiang-kasutamaizu
