### ISSUE TITLE
住箱フィールドワーク記録

### ISSUE THREAD

**Issue by mapconcierge** [furuhashilab/jyubako4dronemapping#30]
「空間情報の共有」授業用最終レポート

**Comment by mizukikakuta** [comment]
最終課題 提出日 2019.1.29
1A116068  角田みずき
先日はゼミで海上自衛隊見学があり、BBQにも参加できず申し訳ありませんでした。最終課題なのですが、自宅(あざみ野)から淵野辺キャンパスまでで調べました。数字もコンピュータでの作業も不得意で、いつも迷惑をかけてしまいましたが、丁寧なご指導ありがとうございました。
最終課題宜しくお願い致します。

◆ジオコード
自宅　　fX139.55717 fY35.56963
あざみ野駅　　fX139.55334      fY35.56825

◆Whats3Words
あざみ野駅　かいじょう・めっきり・ていせい
淵野辺駅　　かんこう・まとう・たまねぎ

◆UTMGrit（地理院地図WEB場所情報コード）
淵野辺駅　00001B000000000309C4EDA6493EFFC0
青学相模原キャンパス　00001B000000000309C4C22649C3FFC0

**Comment by ghost** [comment]
1A116168 西脇奈那

①GeoJSON

https://gist.github.com/nana37/e7858e3b2d5e24d546c4bb5c7685fc17#file-gsi20190130194322942-geojson

②地理院地図

https://gist.github.com/nana37/e1da0838369d584c0ea252aa514ae857#file-gistfile1-txt

③What3Words
淵野辺駅　きのこ・ねどこ・きゅうけい
横須賀駅　あめつぶ・せたい・じまえ

**Comment by Pen-Pento** [comment]
# 1A116044 大越夏音

## Strava: https://www.strava.com/activities/2084386386

## what3words: https://w3w.co/てはず・あかかぶ・あいそ

## Mapillary: https://www.mapillary.com/app/?lat=35.26153739079392&lng=139.73828148109814&z=17&feedItem=user-2SDnvpYvvQ2nkOU9VIsw_g-activity-user-2SDnvpYvvQ2nkOU9VIsw_g-publishing_done-image%3A1548775835109&pKey=xdp-fx1SdikwCbFWhMObxA&focus=photo

**Comment by akitohorinouchi** [comment]
最終課題　1月31日提出
1A116200　堀之内彬人

①Strava
行き：https://www.strava.com/activities/2083980564
帰り：https://www.strava.com/activities/2084395230

②Mapillary
https://www.mapillary.com/app/user/akiaki?lat=35.26163441791591&lng=139.73831099305303&z=17&pKey=hbF31gT2GdXF6xPmSA0-gg&focus=photo

③what3words
柴崎駅：きぼり・うらわざ・きちっと
観音崎公園：はつおん・たしゃ・どんぶり

**Comment by akitohorinouchi** [comment]
最終課題　1月31日提出
1A116200　堀之内彬人

①Strava
行き：https://www.strava.com/activities/2083980564
帰り：https://www.strava.com/activities/2084395230

②Mapillary
https://www.mapillary.com/app/user/akiaki?lat=35.26163441791591&lng=139.73831099305303&z=17&pKey=hbF31gT2GdXF6xPmSA0-gg&focus=photo

③what3words
最寄駅：https://map.what3words.com/きぼり・うらわざ・きちっと
観音崎公園：https://map.what3words.com/はつおん・たしゃ・どんぶり
